package me.rerere.rikkahub.workflow.trigger

import android.util.Log
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.launch
import me.rerere.rikkahub.space.SpaceNotificationDispatcher
import me.rerere.rikkahub.space.SpaceNotificationEntity
import me.rerere.rikkahub.space.SpaceNotificationSink
import me.rerere.rikkahub.space.SpaceRepository
import me.rerere.rikkahub.workflow.model.TriggerSpec
import me.rerere.rikkahub.workflow.model.WorkflowDefinition

/**
 * `space_notification_created` — fires a workflow when Cat Garden notifies its assistant.
 *
 * Two guards make assistant-to-assistant recursion provably terminate rather than merely
 * unlikely:
 *
 *  1. **Causal depth.** A notification whose `origin_depth` is >= 1 was produced by an
 *     automation run, not by the person. Those never wake a workflow. Without this, A
 *     commenting on B wakes B, whose reply comments on A and wakes A, forever — each hop a
 *     fresh notification that no cooldown would stop.
 *  2. **Exactly-once claim.** The notification is claimed through a conditional update before
 *     anything fires; only the caller that observed `consumed_at_ms` as NULL proceeds. A
 *     redelivered or duplicated event therefore cannot run a workflow twice.
 *
 * Self-actions are already absent by construction: the repository writes no notification row
 * when the actor is the recipient.
 *
 * The trigger carries no model-supplied payload. [SpaceNotificationEntity.notificationId] is
 * generated by the runtime from the stored row, and nothing here writes it into an action's
 * arguments — a woken run reads the content back through the space read tools.
 */
internal class SpaceNotificationTriggerFamily(
    private val scope: CoroutineScope,
    /**
     * Resolved on first use rather than at construction. The registry is built during app
     * start-up, and pulling the space repository in eagerly would add a construction-order
     * dependency for something only needed when a notification actually arrives.
     */
    private val repositoryProvider: () -> SpaceRepository,
) : WorkflowTriggerFamily, SpaceNotificationSink {

    override val name = "space_notification"

    @Volatile private var matching: List<WorkflowDefinition> = emptyList()
    @Volatile private var fireCallback: TriggerFireCallback? = null

    override fun handles(spec: TriggerSpec): Boolean = spec is TriggerSpec.SpaceNotificationCreated

    override suspend fun sync(matching: List<WorkflowDefinition>, callback: TriggerFireCallback) {
        this.matching = matching
        this.fireCallback = callback
        SpaceNotificationDispatcher.bind(this)
    }

    override suspend fun shutdown() {
        matching = emptyList()
        fireCallback = null
        SpaceNotificationDispatcher.unbind(this)
    }

    override suspend fun onSpaceNotificationCreated(notification: SpaceNotificationEntity) {
        // Guard 1 — an automation-originated notification never wakes another run.
        if (notification.originDepth >= 1) return

        val cb = fireCallback ?: return
        val snapshot = matching
        if (snapshot.isEmpty()) return

        val fires = snapshot.mapNotNull { workflow ->
            val spec = workflow.trigger as? TriggerSpec.SpaceNotificationCreated
                ?: return@mapNotNull null
            if (!spec.type.isNullOrBlank() &&
                !spec.type.equals(notification.type, ignoreCase = true)
            ) {
                return@mapNotNull null
            }
            workflow.id
        }
        if (fires.isEmpty()) return

        // Guard 2 — claim before firing. A notification that cannot be claimed has already been
        // consumed, so firing again would double-run every matching workflow.
        if (!repositoryProvider().claimNotificationForConsumption(notification.notificationId)) return

        // No explicit dispatcher: the scope already carries one (`Dispatchers.Default` for the
        // trigger registry). Hard-coding IO here would override the scope's own configuration
        // and, incidentally, make the guards untestable without a test-dispatch library.
        scope.launch {
            for (workflowId in fires) {
                val spec = TriggerSpec.SpaceNotificationCreated(
                    type = notification.type,
                )
                runCatching { cb.onFire(workflowId, spec) }.onFailure {
                    Log.w(TAG, "space_notification: fire failed for wf=$workflowId", it)
                }
            }
        }
    }

    private companion object {
        const val TAG = "WorkflowTrigger"
    }
}
