package me.rerere.rikkahub.workflow.trigger

import android.util.Log
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.launch
import me.rerere.rikkahub.space.SpaceActor
import me.rerere.rikkahub.space.SpaceActorKind
import me.rerere.rikkahub.space.SpaceCausalDepth
import me.rerere.rikkahub.space.SpaceNotificationDispatcher
import me.rerere.rikkahub.space.SpaceNotificationEntity
import me.rerere.rikkahub.space.SpaceNotificationSink
import me.rerere.rikkahub.space.SpaceRepository
import me.rerere.rikkahub.workflow.model.TriggerSpec
import me.rerere.rikkahub.workflow.model.WorkflowDefinition

/**
 * `space_notification_created` — fires a workflow when Cat Garden notifies ITS OWN assistant.
 *
 * Three guards make assistant-to-assistant recursion provably terminate rather than merely
 * unlikely:
 *
 *  1. **Causal depth.** A notification whose `origin_depth` is >= 1 was produced by an automation
 *     run, not by the person. Those never wake a workflow. Without this, A commenting on B wakes
 *     B, whose reply comments on A and wakes A, forever — each hop a fresh notification that no
 *     cooldown would stop. See [SpaceCausalDepth] for the one contract this reads.
 *  2. **Recipient ownership.** The notification must be addressed to the workflow's own
 *     [WorkflowDefinition.authoringAssistantId]. Trigger type alone is not a mailbox: two
 *     assistants can both arm `COMMENT` workflows, and without this guard a comment on A's post
 *     would run B's and C's workflows too. A USER-addressed notification never reaches an
 *     assistant workflow at all, and a legacy workflow with no authoring assistant fails closed
 *     rather than guessing which inbox it belongs to.
 *  3. **Exactly-once claim.** The notification is claimed through a conditional update before
 *     anything fires; only the caller that observed `consumed_at_ms` as NULL proceeds. A
 *     redelivered event, or the same row replayed after a restart, therefore cannot run a workflow
 *     twice.
 *
 * Self-actions are already absent by construction: the repository writes no notification row when
 * the actor is the recipient.
 *
 * The claim above is exactly-once *claiming*. It is taken before the run is handed off, so a
 * process that dies in between loses that fire — delivery is at-most-once, and a failing action
 * is not retried. What is guaranteed is that one notification never produces two fires.
 *
 * **Durable delivery.** [SpaceNotificationDispatcher] is a process-local signal, so a notification
 * created while this family was unbound, or while the app was dead, arrives as no event at all.
 * [sync] therefore replays [SpaceRepository.listPendingNotifications] across the unmatched window
 * and feeds every row back through [onSpaceNotificationCreated]. The durable row is the source of
 * truth; the dispatcher only saves the round trip when it does happen to be listening.
 *
 * The trigger carries no model-supplied payload. [SpaceNotificationEntity.notificationId] is
 * generated by the runtime from the stored row, and nothing here writes it into an action's
 * arguments — a woken run reads the content back through the space read tools.
 */
internal class SpaceNotificationTriggerFamily(
    private val scope: CoroutineScope,
    /**
     * Resolved on first use rather than at construction. The registry is built during app
     * start-up, and pulling the space repository in eagerly would add a construction-order
     * dependency for something only needed when a notification actually arrives.
     */
    private val repositoryProvider: () -> SpaceRepository,
    /** Injectable so the replay window is decided by an assertion rather than by the wall clock. */
    private val nowMs: () -> Long = { System.currentTimeMillis() },
) : WorkflowTriggerFamily, SpaceNotificationSink {

    override val name = "space_notification"

    @Volatile private var matching: List<WorkflowDefinition> = emptyList()
    @Volatile private var fireCallback: TriggerFireCallback? = null

    override fun handles(spec: TriggerSpec): Boolean = spec is TriggerSpec.SpaceNotificationCreated

    override suspend fun sync(matching: List<WorkflowDefinition>, callback: TriggerFireCallback) {
        this.matching = matching
        this.fireCallback = callback
        SpaceNotificationDispatcher.bind(this)
        // Bind first, then drain. A notification committed between "read the pending list" and
        // "bind" would otherwise be lost in the gap; with this ordering it is either already in the
        // scan or delivered by the dispatcher, never neither.
        scope.launch { replayPending(matching) }
    }

    override suspend fun shutdown() {
        matching = emptyList()
        fireCallback = null
        SpaceNotificationDispatcher.unbind(this)
    }

    override suspend fun onSpaceNotificationCreated(notification: SpaceNotificationEntity) {
        // Guard 1 — an automation-originated notification never wakes another run.
        if (!SpaceCausalDepth.mayWakeWorkflow(notification.originDepth)) return

        // Guard 2 — only mail addressed to an assistant can wake an assistant's workflow, and only
        // the one it is addressed to. An unparsable recipient fails closed.
        val recipient = SpaceActor.fromStored(notification.recipientKind, notification.recipientId)
            ?: return
        if (recipient.kind != SpaceActorKind.ASSISTANT) return

        val cb = fireCallback ?: return
        val snapshot = matching
        if (snapshot.isEmpty()) return

        val fires = snapshot.mapNotNull { workflow ->
            val spec = workflow.trigger as? TriggerSpec.SpaceNotificationCreated
                ?: return@mapNotNull null
            // Fail closed on legacy rows: a workflow with no recorded authoring assistant has no
            // inbox to match against, and guessing one would hand it another assistant's mail.
            val owner = workflow.authoringAssistantId?.takeIf { it.isNotBlank() }
                ?: return@mapNotNull null
            if (owner != recipient.id) return@mapNotNull null
            if (!spec.noticeType.isNullOrBlank() &&
                !spec.noticeType.equals(notification.type, ignoreCase = true)
            ) {
                return@mapNotNull null
            }
            workflow.id
        }
        if (fires.isEmpty()) return

        // Guard 3 — claim before firing. A notification that cannot be claimed has already been
        // consumed, so firing again would double-run every matching workflow.
        if (!repositoryProvider().claimNotificationForConsumption(notification.notificationId)) return

        // No explicit dispatcher: the scope already carries one (`Dispatchers.Default` for the
        // trigger registry). Hard-coding IO here would override the scope's own configuration
        // and, incidentally, make the guards untestable without a test-dispatch library.
        scope.launch {
            for (workflowId in fires) {
                val spec = TriggerSpec.SpaceNotificationCreated(
                    noticeType = notification.type,
                )
                runCatching { cb.onFire(workflowId, spec) }.onFailure {
                    Log.w(TAG, "space_notification: fire failed for wf=$workflowId", it)
                }
            }
        }
    }

    /**
     * Re-presents notifications that were committed while nothing was listening.
     *
     * Bounded twice on purpose. Only recipients that some currently-enabled workflow actually
     * belongs to are scanned — an assistant with no armed workflow has no consumer, and scanning
     * for it would be work whose only outcome is a later rescan. And each recipient is scanned over
     * a fixed recent window with a page cap, so a long-dead install cannot turn its first bind
     * after an upgrade into an unbounded replay storm.
     *
     * A replayed row goes through exactly the same guards as a live one: recipient ownership,
     * causal depth, then the same claim. Rows this family declines — wrong type filter, depth >= 1
     * — are left unconsumed rather than claimed, because claiming them would be recording a
     * delivery that never happened.
     *
     * One honest limit: because declined rows stay pending and the scan is oldest-first, a backlog
     * larger than [REPLAY_BATCH] of rows that will never match (say, every LIKE notification for an
     * assistant whose only workflow filters COMMENT) can occupy a whole batch. The starvation is
     * bounded by [REPLAY_WINDOW_MS] — once those rows age out, replay moves on — and it only ever
     * delays REPLAY. A row created while this family is bound is delivered live and never touches
     * this path at all. That is why the cap is logged rather than silently applied.
     */
    private suspend fun replayPending(matching: List<WorkflowDefinition>) {
        val recipients = matching
            .mapNotNull { workflow -> workflow.authoringAssistantId?.takeIf { it.isNotBlank() } }
            .distinct()
        if (recipients.isEmpty()) return
        val repository = runCatching { repositoryProvider() }.getOrNull() ?: return
        val sinceMs = nowMs() - REPLAY_WINDOW_MS
        for (assistantId in recipients) {
            val recipient = SpaceActor.fromAssistant(assistantId) ?: continue
            val pending = runCatching {
                repository.listPendingNotifications(recipient, sinceMs, REPLAY_BATCH)
            }.getOrNull() ?: continue
            if (pending.size >= REPLAY_BATCH) {
                Log.w(
                    TAG,
                    "space_notification: replay hit its $REPLAY_BATCH-row cap for " +
                        "assistant=${assistantId.take(8)}; older rows stay pending",
                )
            }
            for (notification in pending) {
                runCatching { onSpaceNotificationCreated(notification) }.onFailure {
                    Log.w(TAG, "space_notification: replay failed for ${notification.notificationId}", it)
                }
            }
        }
    }

    private companion object {
        const val TAG = "WorkflowTrigger"

        /**
         * How far back a bind will look. A notification older than this is treated as expired
         * rather than as a pending obligation: firing a day-old LIKE long after the moment it
         * referred to is not the event anyone wanted, and the window keeps the first bind after a
         * long absence cheap.
         */
        const val REPLAY_WINDOW_MS = 24 * 60 * 60 * 1000L
        const val REPLAY_BATCH = 50
    }
}
